<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="cs" xml:lang="cs">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="cs"/>

<?php if ($this->menu_refresh > 0) {
    

    echo '<meta http-equiv="refresh" content="'. $this->menu_refresh .'">';
 

    }
?>
<meta name="keywords"
	content="<?php echo $this->keyword; ?>" />

<meta name="description"
	content="<?php
	
	if ($this->description) {
		echo $this->description;
	}else {
		//echo "Lavazza Service portal";
	}
	
	?>" />
	
<?php if ($this->alerts != null) {
    ?>
    <script>
        //window.popup = window.open($(this).attr('href'), 'Ad', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0');
        //$(window.popup).onload = function()
    //            {
    //            alert("Popup has loaded a page");
    //        };

    
    window.open("http://panika.knihovnakv.cz/panika/", "panika", "width=700,height=700,left=150,top=150,toolbar=1,resizable=0");
    
        
    </script>
<?php     
}	


?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl?>/public/styles/styl.css" />

<title><?php
echo $this->title ?>

    </title>
</head>
<body>


<div id="container" style="width:1000px;">
		<div class="DivCenter">
			<?php /*<img style="margin-bottom:10px;"  src="<?php echo $this->baseUrl?>/public/images/styl/main_head.gif" alt="" title="" />*/ ?>
		</div>

		<div class="menuBack" >
        <?php
		  if (Zend_Auth::getInstance()->hasIdentity() == true) {
		      ?>

		         <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/index/">Domů</a>
		         <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/nastaveni"><?php echo $this->cele_jmeno?> - Nastavení </a>
		         
				 <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/Login/odhlaseni">ODHLÁŠENÍ</a>		
				 
				 <?php /* 
				 <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/">Hledat</a>
                 <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/editace/novy-stroj">Nový stroj</a>
				 <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/index/kompletni-seznam">Kompletní seznam</a>
				 <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/report/stroje-v-poruse">Stroje v poruše</a>
				 <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/report/stroje-k-servisu">Stroje k servisu</a>
				 <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/report/stroje-bez-intervalu">Stroje bez intervalu</a>
				 <a style="margin-left:25px;margin-right:25px; color:white;" href="<?php echo $this->baseUrl?>/Login/odhlaseni">ODHLÁŠENÍ</a>
				 */
				 ?>
		  <?php }

		  ?>

		</div>		

		
		<?php //<div class="error" id="main"> ?>
			<div class="m-bg-1">
			<div class="m-bg-2">
			<div class="m-bg-3">
	      	<?php /*<div style="margin-left: 25px; margin-right: 25px; width: 100px;" > */ ?>




	