

	      </div>
		<div class="m-bg-4" >
			<br />
			<br />			<br />
			<br />
		</div>
		</div>
		</div>
		</div>
<?php  		
 //		</div>
		
 //</div> ?>	




<?php /*		</div>
	</div>
	

	<div id="navigation">
	
		<?php
		include ('leve_menu.phtml');
		?> 
		
	</div>
	
	<div class="clearRight"/>
	
	<div id="footer" style="width:100%;float:left;">
		<?php echo " <p>&copy; Miki - 2007</p>" ?>
	</div>	
	

*/ ?>



<?php /*

		$registry = Zend_Registry::getInstance ();
		$config = $registry->get ( "config" );
		
		if ($config->db->profiler == false ) {
			
			echo "</div>
			</div>";
			
			?>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-6640489-2");
pageTracker._trackPageview();
} catch(err) {}</script>			
			
			*/ ?>
		
		
			
			
			

			
			
			
			<?php
		echo"	
		
		
		
		
		
		</body>
			</html>";
		//}

?>



