<?php
echo $this->render ( 'hlavicka.phtml' );
?>


<br />
<br />
<br />

<h1><?php echo $this->title ?> ****</h1><br />


<form action="" method="post">  
	<table>
	  	<tr>
		  	<td>
		  	<?php echo _("Jméno") ?>
	  		</td>
	  	
	  		<td><input class="form_input_login" type="text" name="heslo" size="10"/>
	  		</td>
	  	</tr>
  	<tr>
  	<td colspan="2" align="center"><input class="form_submit_login" type="submit" value="<?php echo _("Generovat SHA");?>"/>
  	</td>
  	</tr>
  	</table>
        
        
  </form>



<?php
echo $this->render ( 'paticka.phtml' );
?>
